### ISSUE TITLE
Fix time display

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/blog#17]
Something is broken in the meta reader, which is why the date is partly broken.
Display on the homepage is like ```2015-04-26 14```

**Comment by Fohlen** [comment]
Fixed with 65a46ff48c14385cd23f61855516e9a0b0c11c72
This was caused by a wrong-intended call of explode which additionally splitted the timestamps as well..
Somehow (even if specified) $limit does not work which is why I fall back to traditionall strpos/substr.
@Croydon maybe timestamps need some formatting now?

**Comment by Croydon** [comment]
It worked before and I highly doubt explode has a bug. http://sandbox.onlinephpfunctions.com/code/743995d557696ac11cf94468394d4436428c85f0 

This didn't even had a limit: https://github.com/inexor-game/blog/commit/65a46ff48c14385cd23f61855516e9a0b0c11c72#diff-32a4fb7204983d3fc1c7b0251c1eb650L21
while my original had one: https://github.com/inexor-game/blog/blob/e333ac93f7e52d9341f9c01e2c1616722269f027/app/readPost.php#L35

If you want two pieces you need the $limit 2.

**Comment by Fohlen** [comment]
Fixed with 34160304025a684b038058e05cd36f4859ad5111
