### ISSUE TITLE
Headlines should have a (bigger) top margin

### ISSUE THREAD

**Issue by Croydon** [inexor-game/blog#22]
Headlines in the blog have no or at least no visible top margin, which disturbs the typography. There should be a visible gap between the last paragraph and a new headline.

**Comment by Fohlen** [comment]
Fixed by ce82c93 although I accidentally specified the wrong issue number

**Comment by Croydon** [comment]
FYI You also forgot the # - you always need it to refer to an issue (or PR) - e.g. #22
