### ISSUE TITLE
Add a blog-only overview

### ISSUE THREAD

**Issue by Croydon** [inexor-game/blog#8]
Add a blog-only overview + a specific-year-only-overview.

**Comment by Fohlen** [comment]
Blog only overview is added. We need to enhance this feature with the search (maybe using fatfree's JIG database as a backend provider).

**Comment by Fohlen** [comment]
This also affects #1

**Comment by Fohlen** [comment]
Year only view has been added with c9246c0

**Comment by Croydon** [comment]
One can't see at all that he/she is on a specific year overview. There need always to be some visual feedback/indicator.

**Comment by Fohlen** [comment]
It's within the URI?
```
/blog/2015
/blog/2015/entry
/blog/2014
```

**Comment by Croydon** [comment]
You have think from a user perspective. Users don't want to interpret the URL, the website has to be precisely.
