### ISSUE TITLE
Refactor the meta system.

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/blog#9]
By now there are some hardcoded flaws in the meta system. Try to refactor stuff..

**Comment by Croydon** [comment]
Currently it's lagging a way how we can set default values or do something with the value, e.g. nickname mapping before we return the value. That's the reason why I hardcoded it.

We can overcome the first problem by simple define a default $meta array.

**Comment by Fohlen** [comment]
Solved with 71f57fc645c45f9df0660ef81c6ae2509ddae8fd
This could be (optionally) enhanced by adding default values to a config file (eg config.ini) although I can't think of any real use in the future..
